name: Terraform CI

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Validate, Lint & Checkov
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -migrate-state

      - name: Terraform Validate
        run: terraform validate

      - name: TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      - run: tflint --recursive

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .

      - name: Terraform Plan
        run: terraform plan -lock=false -input=false
